version: '3.9'
networks:
  student-accommodation:
    driver: bridge

services:
  server:
    container_name: server
    image: sirsanctified/server:latest
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - student-accommodation
    env_file:
      - ./backend/.env
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./backend
          ignore:
            - venv/
        - action: rebuild
          path: ./backend/requirement.txt

  client:
    container_name: client
    image: sirsanctified/client:latest
    build: ./client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    networks:
      - student-accommodation
    depends_on:
      - server
    develop:
      watch:
        - action: sync
          path: ./client
          target: /src
          ignore:
            - node_modules/
        - action: sync
          path: ./client
          target: /public
          ignore:
            - node_modules/
        - action: rebuild
          path: ./client/package.json
        

  db:
    container_name: db
    image: postgres
    ports:
      - "6543:5432"
    networks:
      - student-accommodation
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    networks:
      - student-accommodation
    env_file:
      - ./backend/.env
    depends_on:
      - db

volumes:
  db: 