name: Code Style Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    name: Check Formating
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Format Code with Prettier and Lint with Eslint
        run: |
          cd ./client
          npm install
          npm install eslint-config-prettier@latest --save-dev
          npm install eslint-config-airbnb@latest eslint@latest eslint-plugin-import@latest eslint-plugin-jsx-a11y@latest eslint-plugin-react@latest eslint-plugin-react-hooks@latest --save-dev
          npm run lint

        continue-on-error: False

      - name: Check Python Code with Black
        run: |
          cd ./backend
          pip install -r requirements.txt
          pip install black
          black . --check

        continue-on-error: False
